name: accessibility-insights-ci
on:
  check_run:
    types: [completed]

jobs:
    accessibility-scan:
        if: ${{ github.event.check_run['name'] == 'AdaptiveCards-NodeJS-Daily' }}
        runs-on: ubuntu-latest
        steps:
            - name: Get PR number
              # Github recommends pinning third-party actions by full SHA
              uses: jwalton/gh-find-current-pr@6025da8f655f241d580c1b3a07f2f0a781349ed8
              id: findPr

            - name: Scan for accessibility issues
              uses: microsoft/accessibility-insights-action@v2
              with:
                  url: https://adaptivecardsci.z5.web.core.windows.net/pr/${{ steps.findPr.outputs.number }}/samples
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  discovery-patterns: https://adaptivecardsci.z5.web.core.windows.net/pr/${{ steps.findPr.outputs.number }}/samples[.*]

            - name: Upload report artifact
              uses: actions/upload-artifact@v2
              with:
                  name: accessibility-reports
                  path: ${{ github.workspace }}/_accessibility-reports
